/**
 * Copyright (c) 2014-16 Sualeh Fatehi
 * All Rights Reserved
 * 
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package us.fatehi.drools_intro;

import us.fatehi.drools_intro.fact.ProcessState;
import us.fatehi.drools_intro.fact.ProcessState.State;

/*
This is the simplest example of a Drools file, using one single fact 
object, called ProcessState. The “Run” rule fires, and updates the fact, 
causing the “Abort” rule to fire.
*/

rule "Run"
 when
   fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
 then
   fact.setName("Running");
   fact.setState(State.RUNNING);
   update(fact);
end

rule "Abort"
 when
   fact: ProcessState(name == "Running", state == State.RUNNING)
 then
   fact.setName("Aborted");
   fact.setState(State.ABORTED);
   update(fact);
end
