package com.sample;

import com.sample.fact.ProcessState;
import com.sample.fact.ProcessState.State;

rule "Run"
  when
      fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
      System.out.println("Rule fired \"Run\": fact matched " + fact);
      fact.setName("Running");
      fact.setState(State.RUNNING);
      update(fact);
      System.out.println("Rule \"Run\": after update " + fact);
end

rule "Abort"
  when
      fact: ProcessState(name == "Running", state == State.RUNNING)
  then
      System.out.println("Rule fired \"Abort\": fact matched " + fact);
      fact.setName("Aborted");
      fact.setState(State.ABORTED);
      update(fact);
      System.out.println("Rule \"Abort\": after update " + fact);
end
