/**
 * © Copyright 2014 Sualeh Fatehi
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package com.sample;

import com.sample.fact.ProcessState;
import com.sample.fact.ProcessState.State;

/**
We have deliberately caused repeated activation of the “Run” rule, by 
changing something in the fact that is not used by the rule to match the 
fact. This is resolved by setting “no-loop true”.
*/

rule "Run"
no-loop true
  when
      fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
      System.out.println("Rule fired \"Run\": fact matched " + fact);
      fact.setNotes("Running");
      update(fact);
      System.out.println("Rule \"Run\": after update " + fact);
end

rule "Abort"
  when
      fact: ProcessState(name == "Running", state == State.RUNNING)
  then
      System.out.println("Rule fired \"Abort\": fact matched " + fact);
      fact.setName("New Process");
      fact.setState(State.NOT_STARTED);
      update(fact);
      System.out.println("Rule \"Abort\": after update " + fact);
end
