/**
 * © Copyright 2014 Sualeh Fatehi
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package com.sample;

import com.sample.fact.ProcessState;
import com.sample.fact.ProcessState.State;

/**
We have deliberately caused repeated activation of the “Run” rule, by 
changing something in the fact that is not used by the rule to match the 
fact. This is resolved by setting “no-loop true”.
*/

rule "Run"
no-loop true
 when
   fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
 then
   System.out.println("** Fired rule \"Run\" on fact " + fact);
   fact.setNotes("Running");
   update(fact);
   System.out.println(" > Rule \"Run\" modified fact to " + fact);
end

rule "Abort"
 when
   fact: ProcessState(name == "Running", state == State.RUNNING)
 then
   System.out.println("** Fired rule \"Abort\" on fact " + fact);
   fact.setName("New Process");
   fact.setState(State.NOT_STARTED);
   update(fact);
   System.out.println(" > Rule \"Abort\" modified fact to " + fact);
end
