/**
 * © Copyright 2014-15 Sualeh Fatehi
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package com.sample;

import com.sample.fact.ProcessState;
import com.sample.fact.ProcessState.State;

/**
We have deliberately caused circular activation of the “Run” and “Abort 
rules. This is resolved by setting “lock-on-active true”. This forces a 
rule to activate only once.
*/

rule "Run"
lock-on-active true
 when
   fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
 then
   fact.setName("Running");
   fact.setState(State.RUNNING);
   update(fact);
end

rule "Abort"
lock-on-active true
 when
   fact: ProcessState(name == "Running", state == State.RUNNING)
 then
   fact.setName("New Process");
   fact.setState(State.NOT_STARTED);
   update(fact);
end
