/**
 * © Copyright 2014 Sualeh Fatehi
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package com.sample;

import com.sample.fact.ProcessState;
import com.sample.fact.ProcessState.State;

/*
All the rules can be activated, but Drools has to pick one to go first. Drools 
resolves this conflict using a conflict resolver. Do not write rules that rely 
on a default conflict resolution strategy.
*/

rule "New Process to Process B"
  when
    fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
    System.out.println("** Fired rule \"New Process to Process B\" on fact " + fact);
    fact.setState(State.NOT_STARTED);
    fact.setName("Process B");
    update(fact);
    System.out.println(" > Rule \"New Process to Process B\" modified fact to " + fact);
end

rule "New Process to Process C"
  when
    fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
    System.out.println("** Fired rule \"New Process to Process C\" on fact " + fact);
    fact.setState(State.NOT_STARTED);
    fact.setName("Process C");
    update(fact);
    System.out.println(" > Rule \"New Process to Process C\" modified fact to " + fact);
end

rule "Catch-all"
no-loop true
  when
    fact: ProcessState(state == State.NOT_STARTED)
  then
    System.out.println("** Fired rule \"Catch-all\" on fact " + fact);
    fact.setState(State.NOT_STARTED);
    fact.setName("Process Y");
    update(fact);
    System.out.println(" > Rule \"Catch-all\" modified fact to " + fact);
end
