/**
 * © Copyright 2014-15 Sualeh Fatehi
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package us.fatehi.drools_intro;

import us.fatehi.drools_intro.fact.ProcessState;
import us.fatehi.drools_intro.fact.ProcessState.State;

/*
All the rules can be activated, but Drools has to pick one to go first. Drools 
resolves this conflict using a conflict resolver. Do not write rules that rely 
on a default conflict resolution strategy.
*/

rule "New Process to Process B"
no-loop true
  when
    fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
    fact.setName("Process B");
    update(fact);
end

rule "New Process to Process C"
no-loop true
  when
    fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
    fact.setName("Process C");
    update(fact);
end

rule "Catch-all"
no-loop true
  when
    fact: ProcessState(state == State.NOT_STARTED)
  then
    fact.setName("Process Y");
    update(fact);
end
