/**
 * © Copyright 2014-15 Sualeh Fatehi
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en_US.
 */
package com.sample;

import com.sample.fact.ProcessState;
import com.sample.fact.ProcessState.State;

/*
All the rules can be activated. Since none of them make any updates, all 
get activated, causing confusion and unpredictable results.
*/

rule "New Process to Process B"
no-loop true
  when
    fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
    fact.setState(State.NOT_STARTED);
    fact.setName("Process B");
end

rule "New Process to Process C"
no-loop true
  when
    fact: ProcessState(name == "New Process", state == State.NOT_STARTED)
  then
    fact.setState(State.NOT_STARTED);
    fact.setName("Process C");
end

rule "Catch-all"
no-loop true
  when
    fact: ProcessState(state == State.NOT_STARTED)
  then
    fact.setState(State.NOT_STARTED);
    fact.setName("Process Y");
end
